/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'clothing' : IDL.Null,
  'other' : IDL.Null,
  'furniture' : IDL.Null,
  'stationery' : IDL.Null,
  'textbooks' : IDL.Null,
  'electronics' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'sellerDisplayName' : IDL.Text,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'timestamp' : IDL.Int,
  'category' : Category,
  'imageId' : IDL.Opt(IDL.Text),
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, Category, IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListingsByCategory' : IDL.Func([Category], [IDL.Vec(Listing)], ['query']),
  'getListingsBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'clothing' : IDL.Null,
    'other' : IDL.Null,
    'furniture' : IDL.Null,
    'stationery' : IDL.Null,
    'textbooks' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'sellerDisplayName' : IDL.Text,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'timestamp' : IDL.Int,
    'category' : Category,
    'imageId' : IDL.Opt(IDL.Text),
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          Category,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListingsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getListingsBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };